# Generated by Django 5.2 on 2025-05-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='acessorio',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='acessorio',
            field=models.ManyToManyField(blank=True, to='garagem.acessorio'),
        ),
    ]
